[local]
localhost

[mongodb]
localhost

[mysql]
localhost

[redis]
localhost

[rabbitmq]
localhost

[user]
localhost

[catalogue]
localhost

[cart]
localhost

[shipping]
localhost

[frontend]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.nikitha.fun
CATALOGUE_HOST=catalogue-dev.nikitha.fun
REDIS_HOST=redis-dev.nikitha.fun
USER_HOST=user-dev.nikitha.fun
CART_HOST=cart-dev.nikitha.fun
MYSQL_HOST=mysql-dev.nikitha.fun
SHIPPING_HOST=shipping-dev.nikitha.fun
RABBITMQ_HOST=rabbitmq-dev.nikitha.fun
PAYMENT_HOST=payment-dev.nikitha.fun
